// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Fvc52LTmzLYxnG0W-aNAbojlEoz2AxI',
    appId: '1:959489501986:android:d4caf45d22a148b514537b',
    messagingSenderId: '959489501986',
    projectId: 'gelecege-kos',
    storageBucket: 'gelecege-kos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNhFahFE-hClVVZpe8kO3aBqdO2YmMAKA',
    appId: '1:959489501986:ios:a491a30ca92176fd14537b',
    messagingSenderId: '959489501986',
    projectId: 'gelecege-kos',
    storageBucket: 'gelecege-kos.firebasestorage.app',
    androidClientId: '959489501986-kfj135pd3s2pia7hfb11ppicv518854t.apps.googleusercontent.com',
    iosClientId: '959489501986-uccut91htn2jd7pair3b11805qhnei16.apps.googleusercontent.com',
    iosBundleId: 'com.example.gelecegeKos',
  );
}
